### ISSUE TITLE
Where is the robot code?

### ISSUE THREAD

**Issue by chenjiayi-zxx** [f3rm/f3rm#4]

**Comment by williamshen-nz** [comment]
We are currently working on the public release of the robot code and hope to have it ready before [CoRL](https://www.corl2023.org/) (early November).

**Comment by siddk** [comment]
This is fantastic — looking forward to the release! Out of curiosity, would it be possible to release the demonstration/grasp collection code any sooner?

**Comment by williamshen-nz** [comment]
Thanks! Unfortunately, we won't be able to release the demo collection code sooner, as we're prioritizing the release of the main robot code.

We have been rebuilding our web-based viewer framework which is what powers the VR and demo collection tooling so it's more customizable and easier to use.

**Comment by Gloryseven** [comment]
where is the source code about 'ns-train f3rm'

**Comment by williamshen-nz** [comment]
> where is the source code about 'ns-train f3rm'

`ns-train` is a command from Nerfstudio: https://github.com/nerfstudio-project/nerfstudio

`f3rm` is the method we define in this repo:
- https://github.com/f3rm/f3rm/blob/main/pyproject.toml#L45
- https://github.com/f3rm/f3rm/blob/main/f3rm/f3rm_config.py

Please open a separate issue if you have other questions, as this issue is for the robot code release. Thanks!

**Comment by williamshen-nz** [comment]
The robot code has been released - here is the pull request: #5 
Please see the main [README](https://github.com/f3rm/f3rm) for installation and usage instructions.

@siddk I've created a separate issue for the demo collection code: https://github.com/f3rm/f3rm/issues/6

Closing this issue for now, please open a separate one if you have any problems with running the code.
